config/routes.rb
FormTricks::Application.routes.draw do
  resources :users

  match 'refresh_partial' => 'refresh_partial#index', :as => "refresh_index"
  match '/next_if(.:format)' => 'users#next_if', :as => "next_if"
  match '/clone(.:format)' => 'users#clone', :as => "clone"
  match '/pmap(.:format)' => 'users#pmap', :as => "pmap"
  match '/unlock(.:format)' => 'users#unlock', :as => "unlock"
  match '/isrunning(.:format)' => 'users#isrunning', :as => "isrunning"
  match '/equilibrium(.:format)' => 'users#equilibrium', :as => "equilibrium"
  match ':controller(/:action)(.:format)'

   root :to => 'users#index'

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  attr_accessible :grade, :m_marks, :obtain_marks, :remarks, :student_id, :subject_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :id, :name, :usr_id
  belongs_to :user, :primary_key=>"id", :foreign_key=>"usr_id"
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :id, :name
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :id, :sname
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :preferences, :title, :active, :count
  serialize :preferences
  has_many :photos, :foreign_key => 'usr_id', :primary_key => 'ph_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
 
end

app/controllers/refresh_partial_controller.rb
class RefreshPartialController < ApplicationController
  def index
    @user = User.find_by_id(1)
  end
  
   def load
     @user = User.find_by_id(1)
     @user.update_attribute(:count, @user.count.to_i+1)
      render :partial => "dynamic"
   end
   
   def show
     
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def next_if
    render :partial => "next_if"
  end

  def pmap
    @users = User.all
    render :partial => "pmap"
  end

##--------------------------------------------------------------------##  
  def isrunning
    pids = `ps -e | awk '{print $1}'`
    pid_arr = Array.new
    pids.each_line{|s| pid_arr << s.chomp}
    if pid_arr.include?(@@pid)
      return true
    else
      return false  
    end
  end
  
  def clone
    lock_file = "assets/robots.txt"
    if(File.exist?(lock_file))
      @@pid = File.open(lock_file,"r").read
      if self.isrunning
        puts "pid #{@@pid} is already running"
        
        return false
      else
        puts "Previous job died"
      end
    end  
    newpid = Process.pid
    file = File.open(lock_file,"w")
    file.write("#{newpid}")
    file.close
    puts "pid #{newpid} processing the job..."
    return newpid
    #render :text=>'<pre>'+newpid.to_yaml and return true
   end
  
  def unlock
    lock_file = "public/robots.txt"
    if File.exist?(lock_file)
      File.delete(lock_file)
      return true
    end
  end  
  
  def equilibrium
    render :partial => "equilibrium"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormTricks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/refresh_partial/_dynamic.html.erb
Reloaded: <%= @user.count %>
<br /><br />

<pre>
<h2>Controller:</h2>	
class RefreshPartialController < ApplicationController
   def load
     @user = User.find_by_id(1)
     @user.update_attribute(:count, @user.count.to_i+1)
      render :partial => "dynamic"
   end
end

---------------------------------------------------------------------------
<h2>index.html.erb</h2>
To see Dynamic changes modify database. "No need to refresh view page :)"
<div class="dynamic">&lt;%= render partial: 'dynamic' %&gt;</div>

&lt;script&gt;
$(document).ready(
     function() {
      setInterval(function() {
        $('.dynamic').load('/refresh_partial/load');
    }, 5000);
});
&lt;/script&gt;

---------------------------------------------------------------------------
<h2>Routes:</h2>
match 'refresh_partial' => 'refresh_partial#index', :as => "refresh_index"

</pre>

app/views/refresh_partial/index.html.erb
To see Dynamic changes modify database. "No need to refresh view page :)"
<div class="dynamic"><%= render partial: 'dynamic' %></div>


<script>
$(document).ready(
     function() {
      setInterval(function() {
        $('.dynamic').load('/refresh_partial/load');
    }, 5000);
});
</script>

app/views/users/_equilibrium.html.erb
<pre>
def equi ( a )
   n = a.length
 
    if n==0
        return -1
    end
        sum = 0
        i=0
        for i in 0..n-1
        sum=sum+a[i].to_i
        end
 
        sum_left = 0   
        j=0
        for j in 0..n-1
        sum_right=sum-sum_left-a[j].to_i
            if sum_left == sum_right
            return j
            end
        sum_left=sum_left+a[j].to_i;
        end
        return -1
end






A zero-indexed array A consisting of N integers is given. An equilibrium index of this array is any integer P such that 0 = P < N and the sum of elements of lower indices is equal to the sum of elements of higher indices, i.e.

    A[0] + A[1] + ... + A[P-1] = A[P+1] + ... + A[N-2] + A[N-1].

Sum of zero elements is assumed to be equal to 0. This can happen if P = 0 or if P = N-1.

For example, consider the following array A consisting of N = 7 elements:

    A[0] = -7   A[1] =  1   A[2] = 5
    A[3] =  2   A[4] = -4   A[5] = 3
    A[6] =  0

P = 3 is an equilibrium index of this array, because A[0] + A[1] + A[2] = A[4] + A[5] + A[6].

P = 6 is also an equilibrium index, because: A[0] + A[1] + A[2] + A[3] + A[4] + A[5] = 0 and there are no elements with indices greater than 6.

P = 7 is not an equilibrium index, because it does not fulfill the condition 0 = P < N.

Write a function

    class Solution { public int equi(int[] A); } 

that, given a zero-indexed array A consisting of N integers, returns any of its equilibrium indices. The function should return -1 if no equilibrium index exists.

Assume that:

        N is an integer within the range [0..10,000,000];
        each element of array A is an integer within the range [-2,147,483,648..2,147,483,647].

For example, given array A such that

    A[0] = -7   A[1] =  1   A[2] = 5
    A[3] =  2   A[4] = -4   A[5] = 3
    A[6] =  0

the function may return 3 or 6, as explained above.

Complexity:

        expected worst-case time complexity is O(N);
        expected worst-case space complexity is O(N), beyond input storage (not counting the storage required for input arguments).

Elements of input arrays can be modified.
Copyright 2009–2012 by Codility Limited. All Rights Reserved. Unauthorized copying, publication or disclosure prohibited.
</pre>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :preferences %><br />
    <b>Activity</b>
    <% %w( sun mon tue wed thu fri sat ).each do |day| %>
    <div style="padding: 2px 2px 2px 2em;">
    <%= check_box_tag "user[preferences][]", day, Array(@user.preferences).include?(day) %> 
    <%= { "sun" => "Sunday", "mon" => "Monday", "tue" => "Tuesday", "wed" => "Wednesday", "thu" => "Thursday", "fri" => "Friday", "sat" => "Saturday" }[day] %></div>
    <% end %>
        
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_next_if.html.erb
<pre>
	
<h2>Code:</h2>	
i=0 <br />
loop do<br />
  i+=1<br />
  next if i==3<br />
  print "#{i} "<br />
  break if i==10<br />
end
<h2>Output:</h2>
<b>1 2 4 5 6 7 8 9 10</b>

</pre>

app/views/users/_pmap.html.erb
<h3>User model:</h3>

has_many :photos, :foreign_key => 'usr_id', :primary_key => 'ph_id'


<h3>Photo model:</h3>

belongs_to :user, :primary_key=>"id", :foreign_key=>"usr_id"


<h3>pmap_html.erb</h3>

@users.first.photos

<h3>Action "pmap"</h3>

@users = User.all


<h3>photo object</h3>

<%= debug @users.first.photos %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= link_to 'New User', new_user_path %><br />
<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Active</th>
    <th>Preferences</th>
    <th colspan="3">Action</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.title %></td>
    <td><%= "Active" unless user.active? %></td>
    <td><%= Array(user.preferences).collect(&:titlecase).join(", ") %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'See Dynamic Partial', refresh_index_path %> Auto Reload Partial<br />

<%= link_to 'Next if', next_if_path %><br />

<%= link_to 'Lock', clone_path %> Process.pid is_running or not<br />

<%= link_to 'Multiple rows in a model in form'%><br />

<%= link_to 'map non primary key as foreign key', pmap_path %><br />

<%= link_to 'array equilibrium', equilibrium_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Title:</b>
  <%= @user.title %>
</p>

<p>
  <b>Preferences:</b>
  <%= @user.preferences %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>